### ISSUE TITLE
Installing the fix

### ISSUE THREAD

**Issue by medarob** [SvenJuergens/newsfixfor815#1]
Hi,

I want to install the fix and downloaded the zip file and unpacked the files in the ext folder (TYPO3 9.5.10 composer mode). I activated the extensions and now I get this error message when I want to open the page:

![grafik](https://user-images.githubusercontent.com/33951787/67003486-58849280-f0de-11e9-939d-25d93ff0fc8f.png)

Do you have any info what I can do to make it work?

**Comment by dhuf** [comment]
You probably need to install it over composer or to add the extension to your composer autoload:

```
	"autoload": {
		"psr-4": {
			"SvenJuergens\\Newsfixfor815\\": "web/typo3conf/ext/newsfixfor815/Classes/",
		}
	},
```

and then run composer dumpautoload to generate the autoload file.

**Comment by SvenJuergens** [comment]
@medarob sorry for "late reply". I did not receive a notification and just happened to see the entry here. I hope you were able to solve your problem with the help of @dhuf. btw: many thanks for helping out @dhuf

**Comment by dhuf** [comment]
A pleasure, thanks for the fix
