### ISSUE TITLE
Extension only for 9?

### ISSUE THREAD

**Issue by sypets** [SvenJuergens/newsfixfor815#2]
Hi, I installed the extension but can't really remember what it is supposed to fix. Will update to 10 soon. Is this extension only relevant for TYPO3 9?

Thanks.

**Comment by SvenJuergens** [comment]
Hi Sybille,
This extension was only a small fix for this bug in the News Extension: https://github.com/georgringer/news/issues/815 .
Georg has closed this bug in the meantime and referred to his own [extension](https://github.com/georgringer/extbase_records_with_no_l10n_parent)  which solves the problem not only for the News Extension.

To be honest, I haven't tested it for TYPO3 10 yet, but if the hook in the News Extension doesn't change, it should also work there. If you can and like to test it, feedback is welcome :)

**Comment by sypets** [comment]
Thanks for the hint for the other extension. It seems like that might be a better solution than continuing with this extension if that is a more general fix. I am afraid I have to do some reading first to understand this better. I was hoping the language problems would magically go away in v10 :wink:

**Comment by SvenJuergens** [comment]
hi Sybille,
yes, I think in the long run it is probably better to have a general solution instead of a solution for only one extension :) and maybe, maybe the problem will be completely gone in the 10 or 11 :)
